import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, CalendarDays, Users, Utensils } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const eventTypes = [
  { title: "Office lunches", text: "Thoughtful food that keeps the team together.", image: "/food/catering-buffet.jpg" },
  { title: "Private celebrations", text: "A table that makes your people feel looked after.", image: "/food/jollof-chicken.jpg" },
  { title: "Weddings & milestones", text: "A generous spread for the moments that matter.", image: "/food/banku-tilapia.jpg" },
];

const services = [
  { icon: CalendarDays, title: "Tell us the occasion", text: "Share your date, location, guest count, and what you are imagining." },
  { icon: Utensils, title: "Shape the menu", text: "We will help balance familiar favourites, variety, and practical details." },
  { icon: Users, title: "Enjoy the room", text: "Our goal is for you to host confidently while we care for the food." },
];

export default function CateringPage() {
  return <div className="min-h-screen bg-[#fffdf9] text-[#242323] dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto max-w-[1440px] px-5 pb-12 pt-6 sm:px-8 lg:px-12 lg:pt-10"><div className="relative overflow-hidden rounded-hero bg-[#2f7d4f] text-white"><div className="grid lg:grid-cols-[0.8fr_1.2fr]"><div className="flex flex-col justify-center p-7 sm:p-10 lg:p-14"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-emerald-100">Nuel’s Foodzone Catering</p><h1 className="mt-5 text-5xl font-extrabold leading-[0.98] tracking-[-0.07em] sm:text-7xl">Bring flavor<br />to every<br /><span className="text-orange-200">occasion.</span></h1><p className="mt-6 max-w-md text-base leading-7 text-emerald-50">Your home of quality delicacies for office lunches, private parties, celebrations, and every room that deserves a thoughtful table.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-[10px] bg-[#f15b2a] px-6 text-sm font-extrabold text-white hover:bg-[#d9471e]"><Link href="/contact?topic=catering">Book Catering <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-12 rounded-[10px] border-white/40 bg-transparent px-6 text-sm font-extrabold text-white hover:bg-white hover:text-[#242323]"><Link href="/contact?topic=catering">Ask a question <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div><div className="relative min-h-[340px] overflow-hidden lg:min-h-[560px]"><Image src="/food/catering-buffet.jpg" alt="Ghanaian catering spread ready for an event" fill priority className="object-cover" sizes="(min-width: 1024px) 65vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#2f7d4f]/40 via-transparent to-transparent" /></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">Catering for all your needs</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Whatever the occasion,<br />make it feel special.</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{eventTypes.map((event) => <Link key={event.title} href="/contact?topic=catering" className="group overflow-hidden rounded-brand border border-stone-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative aspect-[1.2/0.85] overflow-hidden"><Image src={event.image} alt={event.title} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(min-width: 768px) 33vw, 100vw" /></div><div className="p-6"><h3 className="text-xl font-extrabold">{event.title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{event.text}</p><span className="mt-5 inline-flex items-center text-sm font-extrabold text-[#f15b2a]">Plan this with us <ArrowRight className="ml-2 h-4 w-4 transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div></section>

    <section className="bg-[#fff5e9]"><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="grid gap-5 lg:grid-cols-3">{services.map(({ icon: Icon, title, text }, index) => <div key={title} className="rounded-brand border border-stone-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-[12px] bg-[#fff0e6] text-[#f15b2a]"><Icon className="h-5 w-5" /></div><span className="text-2xl font-extrabold text-stone-200">0{index + 1}</span></div><h3 className="mt-6 text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p><div className="mt-5 flex items-center gap-2 text-xs font-bold text-[#2f7d4f]"><Check className="h-4 w-4" /> We keep it clear</div></div>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="rounded-hero bg-[#242323] px-6 py-10 text-white sm:px-10 lg:flex lg:items-center lg:justify-between lg:px-14"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-orange-200">Ready to plan?</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold leading-tight tracking-[-0.055em] sm:text-5xl">Tell us about your<br /><span className="text-orange-200">event.</span></h2></div><Button asChild className="mt-8 h-12 rounded-[10px] bg-[#f15b2a] px-6 text-sm font-extrabold text-white hover:bg-[#d9471e] lg:mt-0"><Link href="/contact?topic=catering">Start an enquiry <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
  </main><PublicFooter /></div>;
}
