import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, MessageCircle, UsersRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";
import { cateringPackages } from "@/lib/public-content";

export default function CateringPage() {
  return (
    <div className="min-h-screen bg-[#fffaf4] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
      <section className="relative overflow-hidden bg-stone-950 text-white"><div className="absolute inset-0"><Image src="/food/catering-buffet.jpg" alt="Nuel’s Foodzone catering buffet" fill className="object-cover opacity-70" sizes="100vw" /><div className="absolute inset-0 bg-gradient-to-r from-stone-950 via-stone-950/70 to-stone-950/10" /></div><div className="relative mx-auto max-w-7xl px-4 py-24 sm:px-6 lg:px-8 lg:py-32"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.25em] text-orange-200">Nuel’s Foodzone Catering</p><h1 className="mt-4 font-display text-5xl font-extrabold leading-[1.02] tracking-tight sm:text-6xl">Fill the room with food people are happy to talk about.</h1><p className="mt-6 max-w-xl text-base leading-8 text-stone-200">We help you plan menus that feel generous, familiar, and right for the moment — from team lunches and private parties to weddings and milestone celebrations.</p><Button asChild size="lg" className="mt-8 rounded-full"><Link href="/contact?topic=catering">Start a catering enquiry <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>

      <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.25em] text-primary">Made to fit the occasion</p><h2 className="mt-3 font-display text-4xl font-extrabold tracking-tight">A considered menu. A calm service plan.</h2><p className="mt-5 text-base leading-8 text-stone-600 dark:text-stone-300">Every event starts with a conversation about people, place, timing, dietary needs, and the kind of atmosphere you want guests to feel. We then shape a menu and service approach around it.</p></div><div className="mt-12 grid gap-6 md:grid-cols-3">{cateringPackages.map((item, index) => <article key={item.name} className="rounded-3xl border border-stone-200 bg-white p-7 shadow-sm dark:border-stone-800 dark:bg-stone-950"><div className="flex items-center justify-between"><UsersRound className="h-7 w-7 text-primary" /><span className="text-xs font-bold uppercase tracking-[0.18em] text-stone-500">0{index + 1}</span></div><h3 className="mt-6 text-xl font-bold">{item.name}</h3><p className="mt-3 text-sm leading-7 text-stone-600 dark:text-stone-300">{item.description}</p><p className="mt-5 text-xs font-bold uppercase tracking-[0.18em] text-primary">{item.detail}</p></article>)}</div></section>

      <section className="bg-stone-100/80 py-20 dark:bg-stone-900/60"><div className="mx-auto grid max-w-7xl gap-10 px-4 sm:px-6 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:px-8"><div className="relative min-h-[380px] overflow-hidden rounded-[2rem]"><Image src="/food/waakye-special.jpg" alt="Waakye special plate" fill className="object-cover" sizes="(min-width: 1024px) 45vw, 100vw" /></div><div><p className="text-sm font-bold uppercase tracking-[0.25em] text-primary">What we can help with</p><div className="mt-6 grid gap-4 sm:grid-cols-2">{["Menu planning", "Buffet or plated service", "Delivery and setup", "Guest-count guidance", "Dietary conversations", "On-the-day coordination"].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl bg-white px-4 py-4 text-sm font-semibold dark:bg-stone-950"><span className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-primary"><Check className="h-4 w-4" /></span>{item}</div>)}</div><Button asChild className="mt-8 rounded-full"><Link href="/contact?topic=catering"><MessageCircle className="mr-2 h-4 w-4" /> Tell us about your event</Link></Button></div></div></section>
    </main><PublicFooter /></div>
  );
}
