import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const services = ["Menu planning", "Buffet or plated service", "Delivery and setup", "Guest-count guidance", "Dietary conversations", "On-the-day coordination"];

export default function CateringPage() {
  return <div className="min-h-screen bg-[#f7f3ec] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 pb-16 pt-14 sm:px-8 lg:grid-cols-[1.08fr_0.92fr] lg:items-end lg:px-12 lg:pb-24 lg:pt-24"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">Nuel’s Foodzone / Catering</p><h1 className="mt-6 max-w-3xl font-display text-6xl font-extrabold leading-[0.84] tracking-[-0.08em] sm:text-8xl">Make room<br />for <span className="text-primary">good food.</span></h1><p className="mt-9 max-w-lg text-base leading-8 text-stone-600 dark:text-stone-300">A thoughtful spread changes the energy of a room. We plan the menu, the service, and the details so you can be in the moment.</p><Button asChild className="mt-8 h-11 rounded-none px-5 text-[11px] font-bold uppercase tracking-[0.12em]"><Link href="/contact?topic=catering">Start a catering enquiry <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="relative"><div className="relative aspect-[0.9/1] overflow-hidden bg-stone-900"><Image src="/food/catering-buffet.jpg" alt="A warm Ghanaian catered buffet" fill priority className="object-cover" sizes="(min-width: 1024px) 45vw, 100vw" /></div><div className="absolute -bottom-5 -left-5 bg-[#1b7b55] px-5 py-4 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.18em]">For the room</p><p className="mt-1 font-display text-xl font-bold">Not just the plate.</p></div></div></section>

    <section className="border-y border-stone-300 bg-[#e9e3d8] dark:border-stone-800 dark:bg-stone-900"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[0.7fr_1.3fr] lg:px-12"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">How we think about it</p><p className="mt-5 font-display text-3xl font-extrabold leading-[0.95] tracking-[-0.05em]">The best catering feels effortless because the thinking happened early.</p></div><div className="grid gap-8 sm:grid-cols-3"><div><p className="font-display text-4xl font-extrabold text-stone-300 dark:text-stone-700">01</p><p className="mt-4 font-bold">Listen first</p><p className="mt-2 text-sm leading-6 text-stone-500">Your date, guests, space, and mood shape the brief.</p></div><div><p className="font-display text-4xl font-extrabold text-stone-300 dark:text-stone-700">02</p><p className="mt-4 font-bold">Build the menu</p><p className="mt-2 text-sm leading-6 text-stone-500">We balance favourites, variety, and the practical details.</p></div><div><p className="font-display text-4xl font-extrabold text-stone-300 dark:text-stone-700">03</p><p className="mt-4 font-bold">Care on the day</p><p className="mt-2 text-sm leading-6 text-stone-500">The service should leave you free to host your people.</p></div></div></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-12 px-5 py-20 sm:px-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-center lg:px-12 lg:py-28"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">What we can help with</p><h2 className="mt-5 max-w-md font-display text-5xl font-extrabold leading-[0.9] tracking-[-0.06em]">The details<br />behind the ease.</h2><p className="mt-7 max-w-md text-base leading-8 text-stone-600 dark:text-stone-300">From the first menu sketch to the last serving spoon, we keep the experience grounded in generous Ghanaian food and thoughtful hospitality.</p><Button asChild variant="outline" className="mt-8 h-11 rounded-none border-stone-400 px-5 text-[11px] font-bold uppercase tracking-[0.12em]"><Link href="/contact?topic=catering">Tell us about your event <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="grid border-t border-stone-300 dark:border-stone-800">{services.map((service, index) => <div key={service} className="flex items-center gap-4 border-b border-stone-300 py-5 text-lg font-bold dark:border-stone-800"><span className="flex h-7 w-7 items-center justify-center bg-primary text-white"><Check className="h-4 w-4" /></span><span>{service}</span><span className="ml-auto font-display text-2xl text-stone-300 dark:text-stone-700">0{index + 1}</span></div>)}</div></section>

    <section className="bg-[#151512] text-white"><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-center lg:px-12"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-orange-200">Office lunch / private celebration / wedding & milestone</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-extrabold leading-[0.92] tracking-[-0.05em] sm:text-6xl">Bring us the occasion.<br /><span className="text-orange-200">We will bring the table.</span></h2></div><Link href="/contact?topic=catering" className="inline-flex items-center text-[11px] font-bold uppercase tracking-[0.16em] text-orange-200 hover:text-white">Start the conversation <ArrowDownRight className="ml-2 h-5 w-5" /></Link></div></section>
  </main><PublicFooter /></div>;
}
