import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const gallery = [
  { src: "/food/nuels-dinner-hero.jpg", alt: "A spread of Ghanaian dishes at Nuel’s Foodzone", label: "The Dinner table", note: "Where the story starts", size: "large" },
  { src: "/food/jollof-chicken.jpg", alt: "Jollof rice with grilled chicken and plantain", label: "Jollof / chicken / plantain", note: "A familiar kind of comfort", size: "small" },
  { src: "/food/banku-tilapia.jpg", alt: "Banku with grilled tilapia and pepper sauce", label: "Banku / tilapia / pepper", note: "The plate with a point of view", size: "small" },
  { src: "/food/catering-buffet.jpg", alt: "A catered buffet with Ghanaian dishes", label: "The catering table", note: "Made for the room", size: "wide" },
  { src: "/food/ghanaian-salad.jpg", alt: "Fresh Ghanaian-style salad", label: "Fresh things", note: "The balance on the table", size: "small" },
  { src: "/food/pies-snacks.jpg", alt: "Fish pie, meat pie, spring rolls and samosa", label: "Little bites", note: "For the in-between moments", size: "small" },
];

export default function GalleryPage() {
  return <div className="min-h-screen bg-[#f7f3ec] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-24"><div className="flex flex-col justify-between gap-8 border-b border-stone-300 pb-10 sm:flex-row sm:items-end dark:border-stone-800"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">Nuel’s Foodzone / Journal in pictures</p><h1 className="mt-5 font-display text-6xl font-extrabold leading-[0.85] tracking-[-0.08em] sm:text-8xl">The<br /><span className="text-primary">gallery.</span></h1></div><p className="max-w-sm text-sm leading-7 text-stone-500">Food is visual before it reaches the table. A growing collection of dishes, details, and the generous spaces we help feed.</p></div><div className="mt-12 grid gap-x-6 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{gallery.map((item, index) => <figure key={item.src} className={`${item.size === "large" ? "sm:col-span-2 lg:col-span-3 lg:row-span-2" : item.size === "wide" ? "sm:col-span-2 lg:col-span-2" : ""} ${index % 2 ? "lg:translate-y-8" : ""}`}><div className={`relative overflow-hidden bg-stone-900 ${item.size === "large" ? "aspect-[1.18/1]" : item.size === "wide" ? "aspect-[1.8/1]" : "aspect-[0.92/1]"}`}><Image src={item.src} alt={item.alt} fill className="object-cover grayscale-[20%] transition duration-700 hover:scale-105 hover:grayscale-0" sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" /></div><figcaption className="mt-4 border-t border-stone-300 pt-3 dark:border-stone-800"><div className="flex justify-between gap-4"><span className="text-[11px] font-bold uppercase tracking-[0.16em] text-primary">{item.label}</span><span className="text-[11px] font-bold text-stone-400">0{index + 1}</span></div><p className="mt-2 text-sm text-stone-500">{item.note}</p></figcaption></figure>)}</div><div className="mt-20 border-t border-stone-300 pt-8 dark:border-stone-800"><Link href="/dinner/menu" className="inline-flex items-center text-[11px] font-bold uppercase tracking-[0.16em] text-primary">See what is on the table <ArrowUpRight className="ml-2 h-4 w-4" /></Link></div></main><PublicFooter /></div>;
}
