import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const updates = [
  { number: "01", label: "Dinner update", title: "The Dinner menu is now open for online orders", text: "Browse what is available, build your order, and keep the order number for a smoother collection experience." },
  { number: "02", label: "Catering note", title: "Planning a gathering? Start with the shape of the room", text: "Share your date, guest count, location, and the kind of food you want guests to remember." },
  { number: "03", label: "Coming soon", title: "More stories from the Foodzone table", text: "This space will carry manager-published updates, seasonal offers, opening-hour changes, and restaurant news." },
];

export default function AnnouncementsPage() {
  return <div className="min-h-screen bg-[#f7f3ec] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-24"><div className="grid gap-10 lg:grid-cols-[1fr_0.8fr] lg:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">Nuel’s Foodzone / Journal</p><h1 className="mt-5 max-w-3xl font-display text-6xl font-extrabold leading-[0.84] tracking-[-0.08em] sm:text-8xl">Notes<br />from the<br /><span className="text-primary">table.</span></h1></div><p className="max-w-sm text-sm leading-7 text-stone-500">A place for what is happening at Dinner, what we are planning for Catering, and the ideas that make their way out of the kitchen.</p></div><div className="mt-16 divide-y divide-stone-300 border-y border-stone-300 dark:divide-stone-800 dark:border-stone-800">{updates.map((update) => <article key={update.number} className="group grid gap-6 py-8 md:grid-cols-[80px_0.6fr_1fr_auto] md:items-start"><span className="font-display text-4xl font-extrabold tracking-[-0.06em] text-stone-300 transition-colors group-hover:text-primary dark:text-stone-700">{update.number}</span><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">{update.label}</p><h2 className="mt-3 font-display text-2xl font-bold leading-tight tracking-[-0.03em]">{update.title}</h2></div><p className="max-w-md text-sm leading-7 text-stone-500">{update.text}</p><ArrowDownRight className="hidden h-5 w-5 md:block" /></article>)}</div><section className="mt-20 grid gap-8 bg-[#151512] px-6 py-10 text-white sm:px-10 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-orange-200">For tonight</p><h2 className="mt-4 font-display text-4xl font-extrabold leading-[0.9] tracking-[-0.06em] sm:text-6xl">Read less.<br /><span className="text-primary">Eat better.</span></h2></div><Button asChild className="h-11 rounded-none bg-orange-200 px-5 text-[11px] font-bold uppercase tracking-[0.12em] text-stone-950 hover:bg-white"><Link href="/dinner/menu">Open Dinner menu <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></section></main><PublicFooter /></div>;
}
