import Link from "next/link";
import { ArrowRight, BellRing, CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const updates = [
  { label: "Dinner update", title: "The Dinner menu is now open for online orders", text: "Browse what is available, build your order, and keep the order number for a smoother collection experience.", date: "Now serving", tone: "bg-orange-100 text-orange-900" },
  { label: "Catering", title: "Planning an event? Start early with our team", text: "Share your date, guest count, location, and the kind of food you want guests to remember.", date: "Plan ahead", tone: "bg-emerald-100 text-emerald-900" },
  { label: "Coming soon", title: "More stories from the Foodzone table", text: "This space will carry manager-published updates, seasonal offers, opening-hour changes, and restaurant news.", date: "More to come", tone: "bg-stone-100 text-stone-800" },
];

export default function AnnouncementsPage() {
  return <div className="min-h-screen bg-[#fffaf4] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[0.25em] text-primary">Stay in the loop</p><h1 className="mt-4 font-display text-5xl font-extrabold tracking-tight">Announcements</h1><p className="mt-5 text-base leading-8 text-stone-600 dark:text-stone-300">The latest from Nuel’s Foodzone Dinner and Catering. In the next phase, managers will publish and update this page directly from the back office.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{updates.map((update) => <article key={update.title} className="flex flex-col rounded-3xl border border-stone-200 bg-white p-7 shadow-sm dark:border-stone-800 dark:bg-stone-950"><div className="flex items-center justify-between gap-3"><span className={`rounded-full px-3 py-1 text-xs font-bold ${update.tone}`}>{update.label}</span><span className="text-xs font-semibold text-stone-500">{update.date}</span></div><h2 className="mt-6 text-2xl font-bold leading-tight">{update.title}</h2><p className="mt-4 flex-1 text-sm leading-7 text-stone-600 dark:text-stone-300">{update.text}</p><div className="mt-7 flex items-center gap-2 text-sm font-bold text-primary"><BellRing className="h-4 w-4" /> Nuel’s Foodzone update</div></article>)}</div><section className="mt-12 rounded-[2rem] bg-stone-950 p-8 text-white sm:p-10"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-orange-200"><CalendarDays className="h-4 w-4" /><span className="text-xs font-bold uppercase tracking-[0.2em]">Ready for dinner?</span></div><h2 className="mt-3 text-3xl font-extrabold">Go from update to order in one tap.</h2></div><Button asChild className="w-fit rounded-full"><Link href="/dinner/menu">Open Dinner menu <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section></main><PublicFooter /></div>;
}
