import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const stories = [
  { number: "01", label: "Dinner", title: "A table built around comfort.", text: "Ghanaian favourites, fresh sides, and a menu that knows when to keep things simple.", href: "/dinner", image: "/food/jollof-chicken.jpg" },
  { number: "02", label: "Catering", title: "Food that carries the room.", text: "Menus and service for office tables, family celebrations, and the days worth gathering for.", href: "/catering", image: "/food/catering-buffet.jpg" },
  { number: "03", label: "Journal", title: "Notes from the Foodzone.", text: "What is happening, what is seasonal, and what the team is putting on the table next.", href: "/announcements", image: "/food/waakye-special.jpg" },
];

export default function HomePage() {
  return <div className="min-h-screen bg-[#f7f3ec] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto max-w-[1440px] px-5 pb-16 pt-12 sm:px-8 lg:px-12 lg:pb-24 lg:pt-20"><div className="grid gap-12 lg:grid-cols-[0.88fr_1.12fr] lg:items-end"><div className="max-w-2xl pb-2"><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">Nuel’s Foodzone / Ghanaian kitchen</p><h1 className="mt-7 font-display text-[clamp(4rem,9vw,9.2rem)] font-extrabold leading-[0.82] tracking-[-0.08em]">Food<br /><span className="text-primary">with</span><br />feeling<span className="text-primary">.</span></h1><p className="mt-9 max-w-md text-base leading-8 text-stone-600 dark:text-stone-300">A food family for the everyday table, the big table, and everything that happens around them.</p><div className="mt-8 flex items-center gap-5"><Button asChild className="h-11 rounded-none px-5 text-[11px] font-bold uppercase tracking-[0.12em]"><Link href="/dinner/menu">Order Dinner <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button><Link href="/catering" className="text-[11px] font-bold uppercase tracking-[0.12em] text-stone-600 underline decoration-primary decoration-2 underline-offset-8 hover:text-stone-950 dark:text-stone-300 dark:hover:text-white">Plan a gathering</Link></div></div><div className="relative"><div className="absolute -left-3 -top-3 h-24 w-24 border-l border-t border-primary/60 sm:-left-5 sm:-top-5 sm:h-32 sm:w-32" /><div className="relative aspect-[1.08/1] overflow-hidden bg-stone-900"><Image src="/food/nuels-dinner-hero.jpg" alt="A considered spread of Ghanaian dishes" fill priority className="object-cover" sizes="(min-width: 1024px) 58vw, 100vw" /><div className="absolute bottom-5 left-5 flex items-center gap-3 text-[10px] font-bold uppercase tracking-[0.2em] text-white"><span className="h-2 w-2 rounded-full bg-orange-200" /> Dinner is served</div></div><p className="mt-3 text-right text-[10px] font-bold uppercase tracking-[0.18em] text-stone-400">A little taste of the table / 2026</p></div></div></section>

    <section className="border-y border-stone-300 bg-[#e9e3d8] dark:border-stone-800 dark:bg-stone-900"><div className="mx-auto grid max-w-[1440px] md:grid-cols-3">{[{ label: "Dinner", text: "Order a plate, keep the order number.", href: "/dinner/menu" }, { label: "Catering", text: "Make the room feel looked after.", href: "/catering" }, { label: "Contact", text: "Tell us what you are planning.", href: "/contact" }].map((item, index) => <Link key={item.label} href={item.href} className={`group flex min-h-32 items-end justify-between gap-4 p-6 sm:p-8 ${index > 0 ? "border-t border-stone-300 md:border-l md:border-t-0 dark:border-stone-800" : ""}`}><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">0{index + 1} / {item.label}</p><p className="mt-3 max-w-[220px] font-display text-xl font-bold leading-tight">{item.text}</p></div><ArrowDownRight className="h-5 w-5 transition-transform group-hover:translate-x-1 group-hover:translate-y-1" /></Link>)}</div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="flex flex-col justify-between gap-8 border-b border-stone-300 pb-8 sm:flex-row sm:items-end dark:border-stone-800"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">The Foodzone way</p><h2 className="mt-4 max-w-xl font-display text-4xl font-extrabold leading-[0.95] tracking-[-0.05em] sm:text-6xl">Good food does not need to shout.</h2></div><p className="max-w-xs text-sm leading-7 text-stone-500">It needs a point of view, a generous plate, and a reason to stay at the table a little longer.</p></div><div className="mt-10 divide-y divide-stone-300 dark:divide-stone-800">{stories.map((story) => <Link href={story.href} key={story.number} className="group grid gap-6 py-8 md:grid-cols-[80px_0.8fr_1.1fr_0.9fr] md:items-center"><span className="font-display text-4xl font-extrabold tracking-[-0.06em] text-stone-300 transition-colors group-hover:text-primary dark:text-stone-700">{story.number}</span><div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-primary">{story.label}</p><h3 className="mt-2 font-display text-2xl font-bold tracking-[-0.03em]">{story.title}</h3></div><p className="max-w-md text-sm leading-7 text-stone-500">{story.text}</p><div className="relative hidden aspect-[1.8/1] overflow-hidden md:block"><Image src={story.image} alt={story.title} fill className="object-cover grayscale transition duration-500 group-hover:scale-105 group-hover:grayscale-0" sizes="25vw" /></div></Link>)}</div></section>

    <section className="bg-[#151512] text-white"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_1fr] lg:items-center lg:px-12 lg:py-24"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-orange-200">The dinner table is open</p><h2 className="mt-5 max-w-2xl font-display text-5xl font-extrabold leading-[0.9] tracking-[-0.06em] sm:text-7xl">Come hungry.<br /><span className="text-primary">Leave warmer.</span></h2></div><div className="lg:justify-self-end"><p className="max-w-sm text-base leading-8 text-stone-400">Browse the current Dinner menu, send your order to the kitchen, and keep a clear digital order trail from the first click.</p><Button asChild className="mt-7 h-11 rounded-none bg-orange-200 px-5 text-[11px] font-bold uppercase tracking-[0.12em] text-stone-950 hover:bg-white"><Link href="/dinner/menu">Start an order <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
  </main><PublicFooter /></div>;
}
