import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const experiences = [
  { label: "Dinner", title: "Ghanaian comfort, ready when you are.", text: "Browse the menu, build your order, and get a clear receipt trail from the kitchen to your table.", href: "/dinner/menu", image: "/food/jollof-chicken.jpg" },
  { label: "Catering", title: "A generous table for your people.", text: "Thoughtful menus and dependable service for office lunches, celebrations, and the days worth gathering for.", href: "/catering", image: "/food/catering-buffet.jpg" },
];

export default function HomePage() {
  return <div className="min-h-screen bg-[#f7f3ec] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto max-w-[1440px] px-5 pb-14 pt-6 sm:px-8 lg:px-12 lg:pb-20 lg:pt-8"><div className="relative grid overflow-hidden rounded-hero bg-[#18362b] text-white shadow-[0_18px_60px_rgba(24,54,43,0.18)] lg:min-h-[620px] lg:grid-cols-[0.88fr_1.12fr]"><div className="relative z-10 flex flex-col justify-between p-7 sm:p-10 lg:p-14"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[0.16em] text-orange-100"><Sparkles className="h-3.5 w-3.5" /> Ghanaian kitchen</div><h1 className="mt-8 max-w-xl text-[clamp(3.2rem,6.2vw,6.4rem)] font-extrabold leading-[0.97] tracking-[-0.065em]">Good food,<br /><span className="text-orange-200">made for</span><br />your people.</h1><p className="mt-7 max-w-md text-base leading-7 text-stone-200 sm:text-lg">Nuel’s Foodzone brings together everyday Dinner and thoughtful Catering, with flavour that feels like coming home.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-[10px] bg-orange-200 px-5 text-sm font-bold text-stone-950 hover:bg-white"><Link href="/dinner/menu">Order Dinner <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-12 rounded-[10px] border-white/35 bg-transparent px-5 text-sm font-bold text-white hover:bg-white hover:text-stone-950"><Link href="/catering">Explore Catering <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div></div><div className="mt-12 flex items-center gap-6 border-t border-white/15 pt-5 text-xs text-stone-300 lg:mt-8"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-orange-200" /> Made for the table</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-orange-200" /> Digital receipts</span></div></div><div className="relative min-h-[360px] overflow-hidden lg:min-h-0"><Image src="/food/nuels-dinner-hero.jpg" alt="A generous spread of Ghanaian dishes" fill priority className="object-cover" sizes="(min-width: 1024px) 60vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-r from-[#18362b]/35 via-transparent to-transparent" /><div className="absolute bottom-6 right-6 rounded-full bg-white/90 px-4 py-2 text-[10px] font-bold uppercase tracking-[0.15em] text-stone-900 backdrop-blur-sm">Dinner · Catering</div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Two ways to enjoy us</p><h2 className="mt-3 max-w-xl text-4xl font-extrabold leading-tight tracking-[-0.055em] sm:text-5xl">Your kind of occasion,<br /><span className="text-primary">our kind of care.</span></h2></div><p className="max-w-sm text-sm leading-7 text-stone-500">Whether you are ordering one plate or feeding a room, the promise stays the same: generous food, clear details, and a team that pays attention.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-2">{experiences.map((experience) => <Link key={experience.label} href={experience.href} className="group grid overflow-hidden rounded-brand border border-stone-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg dark:border-stone-800 dark:bg-stone-900 sm:grid-cols-[0.86fr_1.14fr]"><div className="relative min-h-64 overflow-hidden"><Image src={experience.image} alt={experience.title} fill className="object-cover transition duration-700 group-hover:scale-105" sizes="(min-width: 1024px) 25vw, 100vw" /></div><div className="flex flex-col justify-between p-6 sm:p-8"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">{experience.label}</p><h3 className="mt-4 max-w-sm text-2xl font-extrabold leading-tight tracking-[-0.04em] sm:text-3xl">{experience.title}</h3><p className="mt-4 text-sm leading-7 text-stone-500">{experience.text}</p></div><span className="mt-8 flex items-center text-sm font-bold text-stone-900 dark:text-white">Explore {experience.label} <ArrowRight className="ml-2 h-4 w-4 text-primary transition-transform group-hover:translate-x-1" /></span></div></Link>)}</div></section>

    <section className="bg-[#efe6d9] dark:bg-stone-900"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-12 lg:py-20"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-primary">From our kitchen</p><h2 className="mt-3 max-w-2xl text-4xl font-extrabold leading-tight tracking-[-0.055em] sm:text-5xl">Comfort with a little<br /><span className="text-primary">more feeling.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-stone-600 dark:text-stone-300">Come for the smoky jollof, stay for the people around the table. We are building a food brand that feels warm, useful, and genuinely ours.</p><Button asChild variant="outline" className="mt-7 h-11 rounded-[10px] border-stone-400 px-5 text-sm font-bold"><Link href="/gallery">See the Foodzone <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="grid grid-cols-2 gap-4"><div className="relative mt-8 aspect-[0.8/1] overflow-hidden rounded-brand"><Image src="/food/banku-tilapia.jpg" alt="Banku and grilled tilapia" fill className="object-cover" sizes="30vw" /></div><div className="relative aspect-[0.8/1] overflow-hidden rounded-brand"><Image src="/food/ghanaian-salad.jpg" alt="Fresh Ghanaian salad" fill className="object-cover" sizes="30vw" /></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="rounded-hero bg-[#18362b] px-6 py-10 text-white sm:px-10 lg:flex lg:items-center lg:justify-between lg:px-14 lg:py-12"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-orange-200">Ready when you are</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold leading-tight tracking-[-0.055em] sm:text-5xl">Bring your appetite.<br /><span className="text-orange-200">We will bring the table.</span></h2></div><Button asChild className="mt-8 h-12 rounded-[10px] bg-orange-200 px-5 text-sm font-bold text-stone-950 hover:bg-white lg:mt-0"><Link href="/dinner/menu">Start an order <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
  </main><PublicFooter /></div>;
}
