import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, ChevronRight, Clock3, CreditCard, MessageCircle, ShoppingBag, Truck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const steps = [
  { icon: ShoppingBag, title: "Browse the menu", text: "Find a familiar favourite or discover something new." },
  { icon: CreditCard, title: "Build your order", text: "Choose your plates, sides, drinks, and notes." },
  { icon: Truck, title: "Choose your handoff", text: "Select pickup or delivery at checkout." },
  { icon: MessageCircle, title: "Keep your receipt", text: "Receive a clear order number and digital trail." },
];

const featured = [
  { name: "Jollof Rice with Chicken", category: "Dinner favourite", price: "From GH₵70", image: "/food/jollof-chicken.jpg" },
  { name: "Banku & Grilled Tilapia", category: "Made for the table", price: "Order from the menu", image: "/food/banku-tilapia.jpg" },
  { name: "Fresh Ghanaian Salad", category: "Something fresh", price: "From GH₵40", image: "/food/ghanaian-salad.jpg" },
  { name: "Catering for your people", category: "Nuel’s Foodzone Catering", price: "Start an enquiry", image: "/food/catering-buffet.jpg" },
];

export default function HomePage() {
  return <div className="min-h-screen bg-[#fffdf9] text-[#242323] dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto max-w-[1440px] px-5 pb-8 pt-6 sm:px-8 lg:px-12 lg:pt-10"><div className="grid overflow-hidden rounded-hero border border-stone-200 bg-[#fff5e9] shadow-[0_16px_50px_rgba(71,45,28,0.08)] lg:grid-cols-[0.88fr_1.12fr]"><div className="flex flex-col justify-center p-7 sm:p-10 lg:p-16"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">Nuel’s Foodzone · Dinner & Catering</p><h1 className="mt-5 max-w-xl text-[clamp(3.15rem,6vw,6.6rem)] font-extrabold leading-[0.96] tracking-[-0.075em]">Your home of<br /><span className="text-[#f15b2a]">quality</span><br />delicacies.</h1><p className="mt-6 max-w-md text-base leading-7 text-stone-600 sm:text-lg">From a warm Dinner plate to a full event spread, we make it easy to enjoy food that feels carefully made and genuinely satisfying.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-[10px] bg-[#f15b2a] px-6 text-sm font-extrabold text-white shadow-sm hover:bg-[#d9471e]"><Link href="/dinner/menu">Order Dinner <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><Button asChild variant="outline" className="h-12 rounded-[10px] border-stone-300 bg-white px-6 text-sm font-extrabold text-[#242323] hover:bg-stone-50"><Link href="/catering">Plan Catering <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-2 text-xs font-bold text-stone-600"><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#2f7d4f]" /> Freshly prepared</span><span className="flex items-center gap-2"><Check className="h-4 w-4 text-[#2f7d4f]" /> Digital receipts</span></div></div><div className="relative min-h-[340px] overflow-hidden bg-[#f6c59c] lg:min-h-[600px]"><Image src="/food/nuels-dinner-hero.jpg" alt="Quality Ghanaian delicacies from Nuel’s Foodzone" fill priority className="object-cover" sizes="(min-width: 1024px) 60vw, 100vw" /><div className="absolute bottom-5 left-5 rounded-[10px] bg-white/95 px-4 py-3 text-xs font-extrabold text-[#242323] shadow-sm backdrop-blur-sm"><span className="block text-[10px] uppercase tracking-[0.15em] text-[#f15b2a]">Made for sharing</span><span className="mt-1 block">Dinner · Catering</span></div></div></div></section>

    <section className="mx-auto grid max-w-[1440px] gap-4 px-5 py-8 sm:grid-cols-3 sm:px-8 lg:grid-cols-3 lg:px-12"><div className="rounded-brand border border-stone-200 bg-white px-6 py-5 shadow-sm"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#f15b2a]">Dinner</p><p className="mt-2 text-lg font-extrabold">Comfort on demand</p><p className="mt-2 text-sm leading-6 text-stone-500">Build an order from the current menu and keep a clear handoff trail.</p></div><div className="rounded-brand border border-stone-200 bg-white px-6 py-5 shadow-sm"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#f15b2a]">Catering</p><p className="mt-2 text-lg font-extrabold">Made for the room</p><p className="mt-2 text-sm leading-6 text-stone-500">Tell us about your occasion and shape a menu that fits your people.</p></div><div className="rounded-brand border border-stone-200 bg-white px-6 py-5 shadow-sm"><p className="text-xs font-extrabold uppercase tracking-[0.16em] text-[#f15b2a]">Quality</p><p className="mt-2 text-lg font-extrabold">Details you can trust</p><p className="mt-2 text-sm leading-6 text-stone-500">Clear order numbers, digital receipts, and manager-led follow-up.</p></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">Simple from start to finish</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">How it works</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-stone-500">A better way to get your food from our kitchen to your table.</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{steps.map(({ icon: Icon, title, text }, index) => <div key={title} className="rounded-brand border border-stone-200 bg-[#fffdf9] p-6 shadow-sm"><div className="flex items-center justify-between"><div className="flex h-11 w-11 items-center justify-center rounded-[12px] bg-[#fff0e6] text-[#f15b2a]"><Icon className="h-5 w-5" /></div><span className="text-2xl font-extrabold text-stone-200">0{index + 1}</span></div><h3 className="mt-6 text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{text}</p></div>)}</div></section>

    <section className="bg-[#fff5e9]"><div className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">From the Dinner menu</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Quality delicacies,<br />ready to order.</h2></div><Button asChild variant="outline" className="h-11 w-fit rounded-[10px] border-stone-300 bg-white px-5 text-sm font-extrabold"><Link href="/dinner/menu">See the full menu <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{featured.map((item) => <Link key={item.name} href={item.name.includes("Catering") ? "/catering" : "/dinner/menu"} className="group overflow-hidden rounded-brand border border-stone-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="relative aspect-[1.05/0.9] overflow-hidden"><Image src={item.image} alt={item.name} fill className="object-cover transition duration-500 group-hover:scale-105" sizes="(min-width: 1024px) 25vw, (min-width: 640px) 50vw, 100vw" /></div><div className="p-5"><p className="text-[10px] font-extrabold uppercase tracking-[0.15em] text-[#f15b2a]">{item.category}</p><h3 className="mt-2 text-lg font-extrabold leading-tight">{item.name}</h3><p className="mt-3 flex items-center justify-between text-sm font-bold text-stone-500"><span>{item.price}</span><ChevronRight className="h-4 w-4 text-[#f15b2a] transition-transform group-hover:translate-x-1" /></p></div></Link>)}</div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="grid gap-5 lg:grid-cols-[1.15fr_0.85fr]"><div className="relative min-h-[360px] overflow-hidden rounded-hero bg-stone-900"><Image src="/food/catering-buffet.jpg" alt="Catering buffet prepared for an event" fill className="object-cover" sizes="(min-width: 1024px) 65vw, 100vw" /><div className="absolute inset-0 bg-gradient-to-t from-stone-950/80 via-stone-950/10 to-transparent" /><div className="absolute bottom-7 left-7 text-white sm:bottom-10 sm:left-10"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-orange-200">Nuel’s Foodzone Catering</p><h2 className="mt-3 max-w-lg text-4xl font-extrabold leading-tight tracking-[-0.05em] sm:text-5xl">Bring the occasion.<br />We will bring the table.</h2><Button asChild className="mt-6 h-11 rounded-[10px] bg-[#f15b2a] px-5 text-sm font-extrabold hover:bg-[#d9471e]"><Link href="/contact?topic=catering">Start an enquiry <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div></div><div className="rounded-hero bg-[#2f7d4f] p-7 text-white sm:p-10"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-emerald-100">Made for your people</p><h2 className="mt-4 text-4xl font-extrabold leading-tight tracking-[-0.05em]">Office lunches.<br />Private parties.<br />Big celebrations.</h2><p className="mt-6 text-sm leading-7 text-emerald-50">Tell us the date, guest count, and the kind of experience you want to create. We will help you take it from idea to table.</p><Link href="/catering" className="mt-8 inline-flex items-center text-sm font-extrabold text-white underline decoration-orange-200 decoration-2 underline-offset-8">Explore Catering <ArrowRight className="ml-2 h-4 w-4" /></Link></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 pb-14 sm:px-8 lg:px-12 lg:pb-20"><div className="rounded-hero bg-[#242323] px-6 py-10 text-white sm:px-10 lg:flex lg:items-center lg:justify-between lg:px-14"><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-orange-200">Your next table starts here</p><h2 className="mt-3 max-w-2xl text-3xl font-extrabold leading-tight tracking-[-0.055em] sm:text-5xl">Come hungry.<br /><span className="text-orange-200">Leave satisfied.</span></h2></div><Button asChild className="mt-8 h-12 rounded-[10px] bg-[#f15b2a] px-6 text-sm font-extrabold text-white hover:bg-[#d9471e] lg:mt-0"><Link href="/dinner/menu">Order Dinner <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div></section>
  </main><PublicFooter /></div>;
}
