import Image from "next/image";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Clock3, ReceiptText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const menuNotes = [
  ["01", "Browse", "See what is on the Dinner menu today."],
  ["02", "Build", "Add plates, sides, and something cold."],
  ["03", "Follow", "Keep your order number from queue to handoff."],
];

export default function DinnerPage() {
  return <div className="min-h-screen bg-[#f7f3ec] text-stone-950 dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto grid max-w-[1440px] gap-10 px-5 pb-16 pt-14 sm:px-8 lg:grid-cols-[0.82fr_1.18fr] lg:items-end lg:px-12 lg:pb-24 lg:pt-24"><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">Nuel’s Foodzone / Dinner</p><h1 className="mt-6 max-w-2xl font-display text-6xl font-extrabold leading-[0.84] tracking-[-0.08em] sm:text-8xl">The kind<br />of dinner<br /><span className="text-primary">you remember.</span></h1><p className="mt-9 max-w-md text-base leading-8 text-stone-600 dark:text-stone-300">Ghanaian favourites, generous plates, and fresh things for the middle of the table. Order ahead or come as you are.</p><div className="mt-8 flex flex-wrap items-center gap-5"><Button asChild className="h-11 rounded-none px-5 text-[11px] font-bold uppercase tracking-[0.12em]"><Link href="/dinner/menu">Open the menu <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button><span className="text-[11px] font-bold uppercase tracking-[0.16em] text-stone-500">Pickup · Delivery</span></div></div><div className="relative"><div className="relative aspect-[1.5/1] overflow-hidden bg-stone-900"><Image src="/food/banku-tilapia.jpg" alt="Banku and grilled tilapia" fill priority className="object-cover" sizes="(min-width: 1024px) 60vw, 100vw" /><div className="absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-stone-950/80 to-transparent p-6 text-white"><span className="text-[10px] font-bold uppercase tracking-[0.2em]">Dinner, made visible</span><ArrowDownRight className="h-5 w-5" /></div></div><p className="mt-3 text-right text-[10px] font-bold uppercase tracking-[0.18em] text-stone-400">Banku / grilled tilapia / pepper</p></div></section>

    <section className="border-y border-stone-300 bg-[#e9e3d8] dark:border-stone-800 dark:bg-stone-900"><div className="mx-auto grid max-w-[1440px] md:grid-cols-3">{menuNotes.map(([number, title, text], index) => <div key={number} className={`p-6 sm:p-8 ${index > 0 ? "border-t border-stone-300 md:border-l md:border-t-0 dark:border-stone-800" : ""}`}><p className="font-display text-4xl font-extrabold tracking-[-0.06em] text-stone-300 dark:text-stone-700">{number}</p><p className="mt-5 text-[11px] font-bold uppercase tracking-[0.2em] text-primary">{title}</p><p className="mt-3 max-w-[230px] font-display text-xl font-bold leading-tight">{text}</p></div>)}</div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-28"><div className="grid gap-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-center"><div className="relative aspect-[1.1/1] overflow-hidden bg-stone-900"><Image src="/food/waakye-special.jpg" alt="Waakye special with plantain and egg" fill className="object-cover" sizes="(min-width: 1024px) 55vw, 100vw" /></div><div><p className="text-[11px] font-bold uppercase tracking-[0.24em] text-primary">Why Dinner works</p><h2 className="mt-5 font-display text-4xl font-extrabold leading-[0.92] tracking-[-0.06em] sm:text-6xl">A little less friction.<br />A lot more table.</h2><p className="mt-7 max-w-md text-base leading-8 text-stone-600 dark:text-stone-300">Your order goes into a clear queue, the kitchen can see what needs doing, and you get a secure page with the details. That is how ordering should feel.</p><div className="mt-8 grid gap-4 border-t border-stone-300 pt-5 dark:border-stone-800"><div className="flex gap-4"><Clock3 className="mt-1 h-5 w-5 text-primary" /><div><p className="font-bold">Prepared for the handoff</p><p className="mt-1 text-sm leading-6 text-stone-500">Choose pickup or delivery and we will confirm the practical details.</p></div></div><div className="flex gap-4"><ReceiptText className="mt-1 h-5 w-5 text-primary" /><div><p className="font-bold">Your receipt stays with you</p><p className="mt-1 text-sm leading-6 text-stone-500">Use the secure order link to save or print your Dinner receipt.</p></div></div></div><Button asChild variant="outline" className="mt-8 h-11 rounded-none border-stone-400 px-5 text-[11px] font-bold uppercase tracking-[0.12em]"><Link href="/dinner/menu">See the live menu <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
  </main><PublicFooter /></div>;
}
