import Image from "next/image";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Clock3, ReceiptText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PublicFooter, PublicHeader } from "@/components/public/PublicShell";

const reasons = [
  { title: "Freshly prepared", text: "Ghanaian favourites, fresh sides, and food made for the middle of the table." },
  { title: "Easy to order", text: "Choose your plates, select pickup or delivery, and keep your order number." },
  { title: "Clear receipt trail", text: "Your order details stay available digitally from checkout to handoff." },
];

export default function DinnerPage() {
  return <div className="min-h-screen bg-[#fffdf9] text-[#242323] dark:bg-stone-950 dark:text-stone-100"><PublicHeader /><main>
    <section className="mx-auto max-w-[1440px] px-5 pb-12 pt-6 sm:px-8 lg:px-12 lg:pt-10"><div className="grid overflow-hidden rounded-hero border border-stone-200 bg-[#fff5e9] lg:grid-cols-[0.9fr_1.1fr]"><div className="flex flex-col justify-center p-7 sm:p-10 lg:p-14"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">Nuel’s Foodzone Dinner</p><h1 className="mt-5 text-5xl font-extrabold leading-[0.98] tracking-[-0.07em] sm:text-7xl">Dinner that<br /><span className="text-[#f15b2a]">feels like</span><br />home.</h1><p className="mt-6 max-w-md text-base leading-7 text-stone-600">Your home of quality delicacies, from everyday comfort plates to something worth bringing everyone around for.</p><div className="mt-8 flex flex-wrap gap-3"><Button asChild className="h-12 rounded-[10px] bg-[#f15b2a] px-6 text-sm font-extrabold text-white hover:bg-[#d9471e]"><Link href="/dinner/menu">Open the menu <ArrowRight className="ml-2 h-4 w-4" /></Link></Button><span className="flex items-center text-xs font-bold text-stone-500"><Check className="mr-2 h-4 w-4 text-[#2f7d4f]" /> Pickup · Delivery</span></div></div><div className="relative min-h-[340px] overflow-hidden bg-[#f6c59c] lg:min-h-[520px]"><Image src="/food/banku-tilapia.jpg" alt="Banku and grilled tilapia" fill priority className="object-cover" sizes="(min-width: 1024px) 60vw, 100vw" /><div className="absolute bottom-5 left-5 rounded-[10px] bg-white/95 px-4 py-3 text-xs font-extrabold shadow-sm"><span className="block text-[10px] uppercase tracking-[0.15em] text-[#f15b2a]">On the table</span><span className="mt-1 block">Banku · tilapia · pepper</span></div></div></div></section>

    <section className="mx-auto max-w-[1440px] px-5 py-14 sm:px-8 lg:px-12 lg:py-20"><div className="text-center"><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">A better Dinner handoff</p><h2 className="mt-3 text-4xl font-extrabold tracking-[-0.06em] sm:text-5xl">Good food, less friction.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-stone-500">Everything you need to move from craving to kitchen to table with fewer loose ends.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3">{reasons.map((reason, index) => <div key={reason.title} className="rounded-brand border border-stone-200 bg-white p-6 shadow-sm"><span className="text-2xl font-extrabold text-[#f15b2a]">0{index + 1}</span><h3 className="mt-6 text-lg font-extrabold">{reason.title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{reason.text}</p></div>)}</div></section>

    <section className="bg-[#fff5e9]"><div className="mx-auto grid max-w-[1440px] gap-10 px-5 py-14 sm:px-8 lg:grid-cols-[1.05fr_0.95fr] lg:items-center lg:px-12 lg:py-20"><div className="relative aspect-[1.08/1] overflow-hidden rounded-hero"><Image src="/food/waakye-special.jpg" alt="Waakye special with plantain and egg" fill className="object-cover" sizes="(min-width: 1024px) 55vw, 100vw" /></div><div><p className="text-xs font-extrabold uppercase tracking-[0.18em] text-[#f15b2a]">Built for the table</p><h2 className="mt-3 text-4xl font-extrabold leading-tight tracking-[-0.06em] sm:text-5xl">Your order should feel as considered as the food.</h2><p className="mt-6 text-sm leading-7 text-stone-600">We keep the Dinner journey clear: your menu choice is checked, your order gets a number, and the kitchen has a record to work from.</p><div className="mt-7 grid gap-4 border-t border-stone-200 pt-5"><div className="flex gap-3"><Clock3 className="mt-1 h-5 w-5 text-[#f15b2a]" /><div><p className="font-extrabold">Prepared for the handoff</p><p className="mt-1 text-sm text-stone-500">Choose pickup or delivery and we will confirm the practical details.</p></div></div><div className="flex gap-3"><ReceiptText className="mt-1 h-5 w-5 text-[#f15b2a]" /><div><p className="font-extrabold">Your receipt stays with you</p><p className="mt-1 text-sm text-stone-500">Use the secure order page to keep or print your Dinner details.</p></div></div></div><Button asChild variant="outline" className="mt-8 h-11 rounded-[10px] border-stone-300 bg-white px-5 text-sm font-extrabold"><Link href="/dinner/menu">Browse the menu <ArrowUpRight className="ml-2 h-4 w-4" /></Link></Button></div></div></section>
  </main><PublicFooter /></div>;
}
